[package]
name = "markers"
version.workspace = true
edition.workspace = true
description = "Foxkit Markers - bookmarks and line markers"

[dependencies]
foxkit-core = { path = "../foxkit-core" }

serde.workspace = true
uuid = { version = "1.0", features = ["v4"] }
