[package]
name = "testing"
version.workspace = true
edition.workspace = true
description = "Foxkit Testing - test discovery, running, and UI"

[dependencies]
task = { path = "../task" }
treesitter = { path = "../treesitter" }

tokio.workspace = true
parking_lot.workspace = true
serde.workspace = true

anyhow = "1.0"
tracing = "0.1"
async-trait = "0.1"
regex = "1.10"
