[package]
name = "selection"
version.workspace = true
edition.workspace = true
description = "Foxkit Selection - cursor and selection management"

[dependencies]
foxkit-core = { path = "../foxkit-core" }

serde.workspace = true
