[package]
name = "diff"
version.workspace = true
edition.workspace = true
description = "Foxkit Diff - text diffing and merging"

[dependencies]
foxkit-core = { path = "../foxkit-core" }

serde.workspace = true
