[package]
name = "completion"
version.workspace = true
edition.workspace = true
description = "Foxkit Completion - code completion and IntelliSense"

[dependencies]
foxkit-core = { path = "../foxkit-core" }

serde.workspace = true
parking_lot.workspace = true
