[package]
name = "font-ligatures"
version.workspace = true
edition.workspace = true
description = "Foxkit Font Ligatures - font ligature detection and rendering"

[dependencies]
parking_lot.workspace = true
serde.workspace = true

tracing = "0.1"
