[package]
name = "hover"
version.workspace = true
edition.workspace = true
description = "Foxkit Hover - hover information and quick info"

[dependencies]
foxkit-core = { path = "../foxkit-core" }

serde.workspace = true
parking_lot.workspace = true
