[package]
name = "folding"
version.workspace = true
edition.workspace = true
description = "Foxkit Folding - code folding regions"

[dependencies]
foxkit-core = { path = "../foxkit-core" }

serde.workspace = true
