[package]
name = "formatting"
version.workspace = true
edition.workspace = true
description = "Foxkit Formatting - code formatting and indentation"

[dependencies]
foxkit-core = { path = "../foxkit-core" }

serde.workspace = true
parking_lot.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow = "1.0"
thiserror = "1.0"
